# .github/workflows/front.yml

on:
  push:
    paths:
      - 'front/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Test and Deploy
      - run: |
          cd front/app
          npm i
          npm run build
          npm run test