# .github/workflows/front.yml

on:
  push:
    paths:
      - 'front/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test and Deploy
        run: |
          cd front
          npm i
          npm run build
          npm run test
